# Generated by Django 5.0.3 on 2024-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_sample_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
    ]
