# Generated by Django 5.0.3 on 2024-03-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=100)),
                ('Tags', models.CharField(max_length=100)),
                ('Date', models.DateField(null=True)),
                ('UiD', models.IntegerField()),
                ('Language', models.CharField(max_length=100)),
            ],
        ),
    ]
