# Generated by Django 5.0.3 on 2024-03-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='Date',
        ),
    ]
