# Generated by Django 5.0.3 on 2024-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_sample_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='UiD',
        ),
        migrations.AddField(
            model_name='sample',
            name='DocumentID',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sample',
            name='DocumentTitle',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sample',
            name='Label',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sample',
            name='Question',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sample',
            name='Sentence',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='sample',
            name='SentenceID',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
