# Generated by Django 5.0.3 on 2024-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_sample_language_remove_sample_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='QuestionID',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
