# Generated by Django 5.0.3 on 2024-04-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_preprocessedsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessedsample',
            name='original_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.sample'),
        ),
    ]
